### ISSUE TITLE
Issues after updating the code on 5-01-2016

### ISSUE THREAD

**Issue by sharanpavan** [kalyankk/stumagz-issues#17]
anna bio kottina okate vastadhe and mysettings kottina okate vastadha?????
Anna hyperlink panicheyyatle 404 page lo
 Stumaz??? Endhi
naku write option ekkada kanapadatle
 anna profile pic and cover pic change chesaka chala time tisukuntundhe
 and uploaded succesfull ani vastundhe kanee ade refresh chesaka ravatle

**Comment by kalyankk** [comment]
bio & mySettings are same.
Upadted Stumagz and also link on 404 page.
It took 1.3sec to upload 1,6MB file for me from office network.
